### ISSUE TITLE
[TACKLE-6] Member(s) should be renamed to Member Names in expanded row

### ISSUE THREAD

**Issue by ganeshhubale** [konveyor/tackle-ui#126]
- Create stakeholder groups and add members(stakeholders)
- Expand stakeholder row and see Member(s) [Here it shows names of members. Hence it should be renamed to `Member names` or something else]
- It is duplicating Member(s) column already exists in a row which gives a count.

![mambers-name](https://user-images.githubusercontent.com/25399590/116247465-85603e00-a788-11eb-91d0-fb5920228828.png)

**Comment by mrizzi** [comment]
@ganeshhubale thanks for your suggestion.
Right now the current implementation is aligned with the mockups so to implement your suggestion, we have to have a review with the UX team to have their approval.
We should also consider that this change would require also the modal window for creating a new stakeholder group to be changed because the `Member(s)` label is used there as well.

**Comment by ganeshhubale** [comment]
Coverted to Jira
