### ISSUE TITLE
[TACKLE-6] Stakeholder groups not getting sorted by Member(s) count

### ISSUE THREAD

**Issue by ganeshhubale** [konveyor/tackle-ui#127]
- Stakeholder groups are getting sorted by Member(s) name but not by count

![sort-numner-mamber](https://user-images.githubusercontent.com/25399590/116249241-3ca98480-a78a-11eb-8373-be806c2c5642.png)

**Comment by mrizzi** [comment]
@ganeshhubale I've checked this using latest Ui container image and I didn't manage to reproduce the issue.
I've checked the sorting by members' count is doing the call to the backend using the right sorting parameter and the UI shows the result of the sorting in the expected way.

Here some screenshots from a test environment
![Screenshot from 2021-04-27 17-04-00](https://user-images.githubusercontent.com/7288588/116264840-e719ab80-a77a-11eb-99c4-0fc8abfaf130.png)

![Screenshot from 2021-04-27 17-03-51](https://user-images.githubusercontent.com/7288588/116264870-eb45c900-a77a-11eb-960a-283c3a357283.png)

Please provide further info because I'm not able to reproduce this or close it if it's not an issue using latest UI container image.

**Comment by ganeshhubale** [comment]
Thanks for checking, Marco. It works for me too. Hence closing this issue.
