### ISSUE TITLE
[TACKLE-5] Job function field is not mandatory while creating new stakeholder

### ISSUE THREAD

**Issue by nitishSr** [konveyor/tackle-ui#133]
As per description of [https://issues.redhat.com/browse/TACKLE-5](TACKLE-5), the job function field should be mandatory for a stakeholder.
However, user can create a new stakeholder without assigning job function.
![ui_issue_job_function_mandatory](https://user-images.githubusercontent.com/43022982/116358636-7e364000-a81b-11eb-9556-6c2d38d937ee.png)

**Comment by carlosthe19916** [comment]
Closing this issue because the "Job function" is not mandatory in the mockups provided by the UX team (See the mockups below). We can open this issue again if we think "Job function" must be a mandatory field.

![Screenshot from 2021-05-06 17-17-09](https://user-images.githubusercontent.com/2582866/117323196-f7bed580-ae8e-11eb-9dbf-dca860521a5d.png)
