### ISSUE TITLE
Container images are not being pushed to quay.io when e2e tests fail

### ISSUE THREAD

**Issue by carlosthe19916** [konveyor/tackle-ui#53]
The GH Job in charge of creating the container image and push it to quay.io is not being executed due to failures in the e2e tests.

**Comment by mrizzi** [comment]
This is a temporary workaround while the e2e tests are refactored to make them more stable and reliable.
In the meantime we must be able to push container images anyway so we decided to temporary remove the container creation dependency upon the successful tests execution.

The issue #57 has been created in order to not forget about restoring the right process.
